php-version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = ['**/*.view.php']

[formatter]
print-width = 180
tab-width = 4
use-tabs = false
space-after-logical-not-unary-prefix-operator = true
null-type-hint = "question"
space-before-arrow-function-parameter-list-parenthesis = true
always-break-named-arguments-list = false
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true
empty-line-after-opening-tag = false

[linter.rules]
interface-name = { psr = false } # this convention is bad
trait-name = { psr = false } # this convention is bad
class-name = { psr = false } # this convention is bad
literal-named-argument = { enabled = false } # https://github.com/carthage-software/mago/issues/693
prefer-first-class-callable = { enabled = false } # bugged, will activate when PFA lands
no-shorthand-ternary = { enabled = false } # those are fine
no-assign-in-condition = { enabled = false } # this is fine as well
too-many-properties = { enabled = false } # does not work well with data objects
excessive-parameter-list = { enabled = false } # does not work well with data objects
